<?php
/**
 * ActiveDaysTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Persona
 *
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ActiveDaysTest Class Doc Comment
 *
 * @category    Class
 * @description ActiveDays
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ActiveDaysTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ActiveDays"
     */
    public function testActiveDays()
    {
    }

    /**
     * Test attribute "mon"
     */
    public function testPropertyMon()
    {
    }

    /**
     * Test attribute "tue"
     */
    public function testPropertyTue()
    {
    }

    /**
     * Test attribute "wed"
     */
    public function testPropertyWed()
    {
    }

    /**
     * Test attribute "thu"
     */
    public function testPropertyThu()
    {
    }

    /**
     * Test attribute "fri"
     */
    public function testPropertyFri()
    {
    }

    /**
     * Test attribute "sat"
     */
    public function testPropertySat()
    {
    }

    /**
     * Test attribute "sun"
     */
    public function testPropertySun()
    {
    }
}
