<?php
/**
 * NewDeliveryReclamationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PersonaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Persona
 *
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PersonaClient;

use PHPUnit\Framework\TestCase;

/**
 * NewDeliveryReclamationTest Class Doc Comment
 *
 * @category    Class
 * @description Data for a delivery reclamation creation.
 * @package     PersonaClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NewDeliveryReclamationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewDeliveryReclamation"
     */
    public function testNewDeliveryReclamation()
    {
    }

    /**
     * Test attribute "paper"
     */
    public function testPropertyPaper()
    {
    }

    /**
     * Test attribute "publication_date"
     */
    public function testPropertyPublicationDate()
    {
    }

    /**
     * Test attribute "claim"
     */
    public function testPropertyClaim()
    {
    }

    /**
     * Test attribute "door_code"
     */
    public function testPropertyDoorCode()
    {
    }
}
