<?php
/**
 * NewsletterSubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PersonaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Persona
 *
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PersonaClient;

use PHPUnit\Framework\TestCase;

/**
 * NewsletterSubscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description NewsletterSubscription
 * @package     PersonaClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NewsletterSubscriptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewsletterSubscription"
     */
    public function testNewsletterSubscription()
    {
    }

    /**
     * Test attribute "list_name"
     */
    public function testPropertyListName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "subscribed"
     */
    public function testPropertySubscribed()
    {
    }
}
