<?php
/**
 * PastTemporaryAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PersonaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Persona
 *
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PersonaClient;

use PHPUnit\Framework\TestCase;

/**
 * PastTemporaryAddressTest Class Doc Comment
 *
 * @category    Class
 * @description Data for previously used temporary addresses
 * @package     PersonaClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PastTemporaryAddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PastTemporaryAddress"
     */
    public function testPastTemporaryAddress()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "zipcode"
     */
    public function testPropertyZipcode()
    {
    }

    /**
     * Test attribute "city_name"
     */
    public function testPropertyCityName()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "temporary_name"
     */
    public function testPropertyTemporaryName()
    {
    }
}
