<?php
/**
 * SubscriptionPauseEditTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PersonaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Persona
 *
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PersonaClient;

use PHPUnit\Framework\TestCase;

/**
 * SubscriptionPauseEditTest Class Doc Comment
 *
 * @category    Class
 * @description SubscriptionPauseEdit
 * @package     PersonaClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SubscriptionPauseEditTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubscriptionPauseEdit"
     */
    public function testSubscriptionPauseEdit()
    {
    }

    /**
     * Test attribute "old_start_date"
     */
    public function testPropertyOldStartDate()
    {
    }

    /**
     * Test attribute "old_end_date"
     */
    public function testPropertyOldEndDate()
    {
    }

    /**
     * Test attribute "new_start_date"
     */
    public function testPropertyNewStartDate()
    {
    }

    /**
     * Test attribute "new_end_date"
     */
    public function testPropertyNewEndDate()
    {
    }
}
