<?php
/**
 * SubscriptionDatesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Persona
 *
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * SubscriptionDatesTest Class Doc Comment
 *
 * @category    Class
 * @description SubscriptionDates
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SubscriptionDatesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubscriptionDates"
     */
    public function testSubscriptionDates()
    {
    }

    /**
     * Test attribute "len_months"
     */
    public function testPropertyLenMonths()
    {
    }

    /**
     * Test attribute "len_days"
     */
    public function testPropertyLenDays()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {
    }

    /**
     * Test attribute "unpaid_break"
     */
    public function testPropertyUnpaidBreak()
    {
    }

    /**
     * Test attribute "invoicing_start"
     */
    public function testPropertyInvoicingStart()
    {
    }

    /**
     * Test attribute "paid_until"
     */
    public function testPropertyPaidUntil()
    {
    }

    /**
     * Test attribute "suspend"
     */
    public function testPropertySuspend()
    {
    }
}
