<?php
/**
 * AccountApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PersonaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Persona
 *
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PersonaClient;

use \PersonaClient\Configuration;
use \PersonaClient\ApiException;
use \PersonaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  PersonaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountCodeForTokenPost
     *
     * Get a password reset token.
     *
     */
    public function testAccountCodeForTokenPost()
    {
    }

    /**
     * Test case for accountForgotPassPost
     *
     * Forgot Password.
     *
     */
    public function testAccountForgotPassPost()
    {
    }

    /**
     * Test case for accountResetForgottenPasswordPost
     *
     * Reset a forgotten password with a token.
     *
     */
    public function testAccountResetForgottenPasswordPost()
    {
    }
}
