<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Persona
 *
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for usersPost
     *
     * Create a new user..
     *
     */
    public function testUsersPost()
    {
    }

    /**
     * Test case for usersUuidEntitlementGet
     *
     * Get users entitlements..
     *
     */
    public function testUsersUuidEntitlementGet()
    {
    }

    /**
     * Test case for usersUuidGdprPut
     *
     * Updates the GDPR consent settings for a given user..
     *
     */
    public function testUsersUuidGdprPut()
    {
    }

    /**
     * Test case for usersUuidGet
     *
     * Get user by UUID..
     *
     */
    public function testUsersUuidGet()
    {
    }

    /**
     * Test case for usersUuidLegalPut
     *
     * Updates the legal consent settings for a given user..
     *
     */
    public function testUsersUuidLegalPut()
    {
    }

    /**
     * Test case for usersUuidPatch
     *
     * Update a user.
     *
     */
    public function testUsersUuidPatch()
    {
    }

    /**
     * Test case for usersUuidSubscriptionsSubsnoAddressChangePost
     *
     * Make a temporary address change for a subscription.
     *
     */
    public function testUsersUuidSubscriptionsSubsnoAddressChangePost()
    {
    }

    /**
     * Test case for usersUuidSubscriptionsSubsnoPausePost
     *
     * Pause users subscription.
     *
     */
    public function testUsersUuidSubscriptionsSubsnoPausePost()
    {
    }

    /**
     * Test case for usersUuidSubscriptionsSubsnoReclamationPost
     *
     * Create a new delivery reclamation for a subscription.
     *
     */
    public function testUsersUuidSubscriptionsSubsnoReclamationPost()
    {
    }
}
